// English is the canonical source for all bundled user-interface translations.
export const STRINGS = [
'Your music. Your space.', 'Save the songs you love. Keep everything organised.', 'Downloads', 'Saved songs', 'Not downloaded', 'Settings', 'Project', 'Language', 'Search languages', 'Search by name', 'Close', 'Back', 'Choose a language', 'Machine-translated languages may contain mistakes.',
'Paste a Spotify link', 'Track, album or playlist', 'Add to queue', 'Start downloads', 'Pause downloads', 'Resume', 'Retry', 'Retry all', 'Remove', 'Details', 'All downloads', 'In progress', 'Ready', 'Downloading', 'Saved', 'Failed', 'Some songs missing', 'Paused', 'Confirmation needed', 'Preview', 'No songs saved',
'Your queue is empty', 'Copy a Spotify link or paste it here to get started.', 'Nothing here yet', 'Your downloads will appear here.', 'Ready when you are', 'Working on your music', 'Download queue', 'Download progress', 'Saved files', 'No audio files were saved. Retry the failed songs.', 'Existing files are checked before downloading again.',
'Spotify preview', 'Start a download to load its Spotify preview here.', 'Load preview', 'Open in Spotify', 'Preview unavailable? Open Spotify instead.', 'Preview loads automatically when you start. Audio does not autoplay.',
'Your saved songs', 'Only complete, verified audio files appear here.', 'No songs saved yet', 'Completed audio files will appear here. Temporary files never count as saved songs.', 'Check files', 'Checking your files…', 'Search saved songs', 'Play', 'Show in folder', 'Open download folder', 'File not found', 'Saved songs could not be checked. Check the folder and try again.',
'Songs to try again', 'Downloads continue when a song fails. You can retry these songs individually or together.', 'Everything is up to date', 'Songs that could not be downloaded will appear here with a reason.', 'No matching audio source', 'No details were returned by the audio provider.', 'Retry this song', 'Show more',
'YouTube needs your confirmation.', 'Downloads are paused. Complete the check in the YouTube window, then choose “Use session and resume”.', 'Open YouTube', 'Use session and resume', 'YouTube is limiting requests. Wait before trying again.', 'Try again later', 'Your completed songs are safe.', 'Confirm YouTube manually', 'Complete the check below yourself. This shares only this window’s YouTube cookies with local downloads until the app closes.', 'YouTube could not be loaded. Check your connection and reopen this window.', 'Session ready',
'Output', 'Audio format', 'Audio quality', 'Automatic', 'Source quality matters; a higher bitrate cannot improve it.', 'Download folder', 'Choose folder', 'New downloads use this folder. Resuming keeps the original location.', 'Appearance', 'System', 'Light', 'Dark', 'Clipboard', 'Automatically paste copied Spotify links', 'Existing input is kept. Downloads start only when you choose.', 'Automatically load Spotify preview on start', 'A new Spotify link is on your clipboard.', 'Use copied link', 'Spotify link pasted. Ready to add.', 'Added to your queue.',
'Download components', 'Checking components…', 'Ready for downloads', 'A download component needs attention.', 'Download components are missing. Please install a complete desktop package.', 'YouTube session', 'Clear session', 'You can complete a requested YouTube check in the app. Confirmation does not guarantee access.', 'About', 'Published by Jedi Meister', 'Original app code licensed under MIT.', 'Spotify supplies metadata. Audio comes from matching YouTube sources. Availability and versions may differ.', 'Download only content you own or have permission to save.',
'Download log', 'Copy diagnostics', 'Diagnostics copied.', 'No messages yet.', 'This file is no longer available. Refresh your saved songs.', 'The audio file could not be opened.', 'The folder could not be opened.', 'The download folder is not writable. Choose another folder in Settings.', 'Pause downloads first.', 'Your queue could not be saved.',
'Get the desktop app', 'A calm workspace for your music.', 'This website is a preview. Audio downloads run in the desktop app.', 'Operating system', 'App version', 'Package', 'Download app', 'All versions on GitHub', 'Choose your Mac chip', 'Choose Apple Silicon or Intel.', 'Windows installer', 'Windows portable', 'Mac · Apple Silicon', 'Mac · Intel', 'Linux · AppImage', 'Linux · Debian / Ubuntu', 'Installer: standard installation. Portable: run without installing. Both are for 64-bit Intel / AMD.', 'Apple menu → About This Mac: look for Apple Silicon or Intel.', 'AppImage works on many Linux distributions. DEB is for Debian and Ubuntu. Both are x86_64.', 'Windows installation help', 'These packages are unsigned. Windows may show “Windows protected your PC”. For a release you trust, choose “More info”, then “Run anyway”.', 'Administrator rights are not required for normal use. If installation needs permission, approve the Windows prompt. For a permission error, choose a writable folder first.', 'No separate Python or FFmpeg installation needed.',
'Please paste a valid Spotify link.', 'Please paste a complete Spotify link.', 'Use a Spotify link to a track, album or playlist.', 'This link is already in your queue.', 'This link is already being processed.', 'Maximum 50 open downloads.', 'Track', 'Album', 'Playlist', 'Session restored. Ready to resume.', 'Ready to start', 'Existing files will be checked when you start.', 'Checking existing files…', 'The download engine could not start.', 'Paused. Completed songs are kept.', 'Paused. Ready to resume.', 'Pausing…', 'Interrupted. You can resume this download.',
'Loading the Spotify track list…', 'Retrying the Spotify connection…', 'Spotify returned no available tracks. Check the link and playlist visibility.', 'Spotify is limiting requests. Wait before resuming.', 'Spotify is not providing this track list. Check that the playlist is public and the link is valid.', 'The Spotify connection failed. Check your connection and try again later.', 'The Spotify track list could not be loaded. See the download log for details.', 'File access failed. Check your download folder and free space.', 'The download engine stopped. See the download log for details.',
'{count} songs', '{count} downloads', '{count} saved', '{count} not downloaded', '{saved} saved · {existing} existing · {skipped} not downloaded', 'Desktop app', 'Web preview', 'Skip to content', 'Free Spotify Downloader home', 'Download again', 'Previous downloads are ready to resume.', 'Temporary working files are stored in app data; finished songs go directly into your download folder.', 'Source unavailable', 'Connection problem', 'No songs match your search', 'Change your search and try again.', 'Audio provider error', 'Cookie session cleared.', 'Download list', 'Version',
"Optional sign-in may reduce CAPTCHAs, but account use can cause temporary or permanent suspension. Avoid your main account; separate accounts are also at risk."
]
